### ISSUE TITLE
Red boxes around unicode characters

### ISSUE THREAD

**Issue by larssp** [JuliaLang/JuliaBox#333]
Issue was stated on the ijulia github page: [#308](https://github.com/JuliaLang/IJulia.jl/issues/308)

A patch for pygments is provided: [Link](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/471/support-unicode-identifiers-in-julia/diff)

Hope to see this resolved on [juliabox.org](https://juliabox.org/), too. Thank you.

![Screenshot](https://cloud.githubusercontent.com/assets/2594443/7467991/d2008d1e-f2b7-11e4-8a66-5709cd9847c6.png)

**Comment by tanmaykm** [comment]
JuliaBox seems to be already having the latest version of pygments (v2.0.2) installed.
Isn't this patch released yet?

Also, I don't see this issue. Is it something browser dependent?
![jbsym](https://cloud.githubusercontent.com/assets/1010989/11245230/9c22d3e8-8e37-11e5-962f-3f96e09676b8.png)

**Comment by jiahao** [comment]
I can't reproduce either. Perhaps OP needs to clear their browser cache?

**Comment by larssp** [comment]
Thanks for the tip jiahao. I cleared my cache in Firefox (42.0) and also tried internet explorer (never visited juliabox with IE before). But I still get the same behaviour.

In the Notebook, everything looks fine
![notebook](https://cloud.githubusercontent.com/assets/15907759/11246187/e64d950a-8e16-11e5-9c5f-34555d1cdd97.PNG)

But if I choose File -> Print Preview the characters get highlighted again:
![highligted](https://cloud.githubusercontent.com/assets/15907759/11246274/4757049e-8e17-11e5-8fb8-bc7dc714c27f.PNG)

It gets highlighted as Errors apparently, if you check the html source
```css
/*# sourceMappingURL=style.min.css.map */
    </style>
<style type="text/css">
    .highlight .hll { background-color: #ffffcc }
.highlight  { background: #f8f8f8; }
.highlight .c { color: #408080; font-style: italic } /* Comment */
.highlight .err { border: 1px solid #FF0000 } /* Error */
...
...
...<span class="err">α</span>...
```


I will see, if I can reproduce this on my private notebook this afternoon.
